### ISSUE TITLE
Add a "status" column to the Version table

### ISSUE THREAD

**Issue by erikbra** [erikbra/grate#112]
Ref. 
* https://github.com/chucknorris/roundhouse/issues/246
* https://github.com/chucknorris/roundhouse/issues/374

**Comment by DjKillerMemeStar** [comment]
Having my first go at contributing to an open source project, also not a Github expert so forgive my mistakes!

I've put a pull request in draft to solve this issue, i still need to write more tests and think about a way to smootly migrate current grate implementations.
https://github.com/erikbra/grate/pull/196

Any feedback is very much welcome!

**Comment by wokket** [comment]
Hey mate,

Good on you for putting your hand up to help.  I'll have a proper look at your PR tonight once I knock off real work!

**Comment by erikbra** [comment]
This should be fixed by #196
