### ISSUE TITLE
Make sure we support Azure SQL databases with all kinds of strange authentication types

### ISSUE THREAD

**Issue by erikbra** [erikbra/grate#115]
Ref. https://github.com/chucknorris/roundhouse/issues/343

* Username/password
* AD username/password
* AD username/password with MFA
* Token
* _others_?

**Comment by wokket** [comment]
I haven't looked in a while, but I thought you _could_ pass tokens on the conn string?

Eg see https://www.connectionstrings.com/ole-db-driver-for-sql-server/azure-active-directory-authentication-with-access-token/

Does the SqlClient parse this differently to OleDB?

**Comment by kimjamia** [comment]
I tried passing that connection string to both `System.Data.SqlClient.SqlConnection` and `Microsoft.Data.SqlClientSqlConnection` and both first complain:
> Keyword not supported: 'provider'

After I remove the "Provider=" part, they both complain:
> Keyword not supported: 'access token'.

Neither list `Access Token` or anything token-related as supported keywords in the documentation.
* [system.data.sqlclient.sqlconnection.connectionstring](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnection.connectionstring?view=dotnet-plat-ext-6.0#remarks)
* [microsoft.data.sqlclient.sqlconnection.connectionstring](https://docs.microsoft.com/en-us/dotnet/api/microsoft.data.sqlclient.sqlconnection.connectionstring?view=sqlclient-dotnet-standard-4.1#remarks)

In both docs, the first sentence is:
> The ConnectionString is similar to an OLE DB connection string, but is not identical.

Also neither [SqlConnectionStringBuilder](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnectionstringbuilder?view=dotnet-plat-ext-6.0&viewFallbackFrom=net-7.0#properties) have any token-related properties.

There was a similar discussion in RH as well: https://github.com/chucknorris/roundhouse/issues/344

**Comment by wokket** [comment]
Just following up on this as I've run across it elsewhere: Modern versions of the SqlClient (as used in grate) have baked in support for acquiring and using tokens without requiring more than a connection string.  See the [MS docco](https://docs.microsoft.com/en-us/sql/connect/ado-net/sql/azure-active-directory-authentication?view=sql-server-ver15#using-active-directory-managed-identity-authentication) for more info.

**Comment by erikbra** [comment]
Nice, thanks, @wokket ! I think this should solve the issue, do you agree, @kimjamia ?

**Comment by erikbra** [comment]
This should Just Work (TM) as of now, all auth methods should be able to specify in the connection string (see e.g. https://learn.microsoft.com/en-us/sql/connect/ado-net/sql/azure-active-directory-authentication?view=sql-server-ver16)
