### ISSUE TITLE
Add support for restoring from backup then migrate

### ISSUE THREAD

**Issue by bptillman** [erikbra/grate#126]
Since this one is a blocker for people at my org giving grate a try, I figured I'd write up an issue to get this tracked. This would mimic the RestoreAndRun mode defined [here](https://github.com/chucknorris/roundhouse/wiki/RoundhousEModes) that Roundhouse has by using some similar [restore configuration options](https://github.com/chucknorris/roundhouse/wiki/ConfigurationOptions#restore-options)

I have already started down the path of implementing this feature, but if you have any thoughts around this @erikbra I am open to discussing it further to make sure it lines up with your ideas around this project before any kind of PR is opened.

**Comment by erikbra** [comment]
Hi, @bptillman , thanks for contributing!

Personally, I have never used the "restore" mode of RoundhousE, so I'm a bit blank to the scenarios it supports, or what people use it for.

My first hunch is that this maybe is something that is better handled outside of grate, as the options for backup and restore are so diverse depending on your environment, i.e. whether you are in the cloud, if you use on-prem databases, and which database you use. Litespeed is mentioned in the RoundhousE docs. I don't have any experience with that tool, but there are probably a lot of different tools available for backup and restore of each of the databases supported in grate.

Could you please give some thoughts around the pros (and cons) of having the restore as an integrated part of grate, compared to handling the restore with your tool of choice (be it cloud restore, litespeed, .bacpac files, copying a sqlite db file, etc) outside of grate?

I'm open to inputs here :)

**Comment by wokket** [comment]
I'll let @bptillman  talk to his side of things, but I know back when we used on-prem databases we used this _all the time_.  Everytime we did a test deploy we'd restore the current prod db to give us as much confidence as possible that everything would be ok at prod deploy time.  Doing this using RH meant we didn't need to build out [custom powershell | TSql+SqlCmd | Custom app | ??]  tooling to get this done, just point RH at the .bak and go.....

**Comment by ajepst** [comment]
@erikbra I think your Cloud-first approach makes sense, but I wouldn't abandon a tool like restore. The "restore" method is particularly useful for onboarding existing projects into roundhouse.  Speaking as a consultant, I frequently encounter projects out there that are sitting on an an on-prem database and where the team currently does manual migrations ad-hoc... and probably don't have their old scripts.  Not only that, they don't know how to cut down their database to be a starter "dev" database.  These are of course problems that need solving, but with restore, you can get them started on roundhouse RIGHT NOW before solving these larger problems, and get them used to the paradigm of scripts going into a database, using a local copy of a db instead of a shared db, etc (these teams almost always use a shared db).   This is actually a critical usage of roundhouse for me. It's a key way we onboard teams to roundhouse with relatively little pain.  In terms of all of the possibilities for where you might restore from... I think a regular sql server backup is the main one that matters.  Teams that are already in the cloud or using newer, cooler stuff are probably in a better starting point than these teams that have this questionable database in an unknown state.  This feature has made the difference between being able to use roundhouse, and not being able to use roundhouse.  Please consider keeping this feature.

Another scenario in which is this can be useful is certain specialized databases in which you really need to have a pretty large chunk of lookup data to be able to do anything at all.  I'm thinking geo databases, etc. Smaller lookup tables are fine to go into scripts, but a backup can be cleaner and faster when you really require a LOT of data even for your local db.

**Comment by bptillman** [comment]
What @ajepst and @wokket stated covers my thoughts around it pretty well actually. To keep this issue as slim as possible, perhaps it could be implemented for just SQL Server bak files, which would cover all of our use cases for this feature and then address adding support for others if its asked for? Or if it has to be keep out of the main code of grate, instead of a developer having to write their own implementation for restoring it could be offered up as an additional grate package they could bring in for just that purpose? I know that idea has been mentioned here before I think, but none currently exist so I'm not sure what other thoughts there are around that.

**Comment by erikbra** [comment]
Hi, again, folx. Thanks for chiming in, and bringing good arguments to the table. I'm of course open to taking this feature in, as long as it's useful to people, and it's not too big of a feature, or too "odd" compared to the other features. I'd be very happy to take a look, @bptillman , how's the implementation going? Is the "restore" functionality a part of Microsoft.Data.SqlClient, or does it require an additional dependency?

 I'd like to simplify the command-line options a bit, though, to just one option, say `--restore <filename>`, or `--restorefrom <filename>`, potentially with a separate timeout option, if needed. I think it's a bit bloated specifying both a "you should do the restore" bool switch, _and_ a "you already know you should restore, but here's the path you need for that" switch, imho.
 
 Thanks for starting the implementation, anyways!

**Comment by docrinehart** [comment]
I'll throw my hat in for another vote on this feature. For the aforementioned geodata and manually migrated database scenarios. Both are in abundant supply in the DoD world...

**Comment by bptillman** [comment]
> 
> 
> Hi, again, folx. Thanks for chiming in, and bringing good arguments to the table. I'm of course open to taking this feature in, as long as it's useful to people, and it's not too big of a feature, or too "odd" compared to the other features. I'd be very happy to take a look, @bptillman , how's the implementation going? Is the "restore" functionality a part of Microsoft.Data.SqlClient, or does it require an additional dependency?
> 
> I'd like to simplify the command-line options a bit, though, to just one option, say `--restore <filename>`, or `--restorefrom <filename>`, potentially with a separate timeout option, if needed. I think it's a bit bloated specifying both a "you should do the restore" bool switch, _and_ a "you already know you should restore, but here's the path you need for that" switch, imho.
> 
> Thanks for starting the implementation, anyways!

The way I was currently looking at implementing it was with a `DbCommand`, similar to the `DropDatabase` method already implemented, and then building up the restore database command text with the file path passed into grate as a command line option. What do you think about that?

I also agree about simplifying things to just have the one `--restore` or `--restorefrom` command line option instead of needing two options to say you are doing a restore.

**Comment by erikbra** [comment]
Yes, that makes sense, just put it after the drop and create here:

![image](https://user-images.githubusercontent.com/1628994/141190437-b8576275-ceb1-44b3-a816-e43455efb7e2.png)

And, in effect, the SQL executed should just be something along the lines of:

```
RESTORE DATABASE FROM DISK = 'C:\MSSQL\Backup\MyDB_full.bak'
```

(replace with the actual file)?

**Comment by bptillman** [comment]
> 
> 
> Yes, that makes sense, just put it after the drop and create here (line 72-ish of GrateMigrator.cs):
> 
> ![image](https://user-images.githubusercontent.com/1628994/141190437-b8576275-ceb1-44b3-a816-e43455efb7e2.png)
> 
> And, in effect, the SQL executed should just be something along the lines of:
> 
> ```
> RESTORE DATABASE FROM DISK = 'C:\MSSQL\Backup\MyDB_full.bak'
> ```
> 
> (replace with the actual file)?

Yup that is exactly where I added the call to restore, if the restore path has been specified, and the code itself is pretty similar. I took a look at how Roundhouse did it and they first set the db to single user, do the restore, then go back to multi user so that is how I have done this as well.
I have it working and did a manual test to prove it works as of right now, but before submitting a PR I am trying to:
1. Do some cleanup
2. Make sure I am properly handling telling the end user if they try to restore on any other db engine that it is not supported currently
3. See if I can figure out how to write a test to actually prove out the restore works.

**Comment by erikbra** [comment]
Very good! :)

Writing a test shouldn't be too hard, should it? You could just include a small .bak file in the repo (if it's not more than some kBs), run a restore, and check that the data from the .bak file is there?

**Comment by erikbra** [comment]
@bptillman - please feel free to give me a shout out if you would like to discuss this more before it is "ready for merge" too. If you like, you can open a pull request, just for the discussion, and we can have a look at it together, if you feel like it.

No pressure, by all means, just if you feel the need to discuss underway 😄

**Comment by bptillman** [comment]
> 
> 
> @bptillman - please feel free to give me a shout out if you would like to discuss this more before it is "ready for merge" too. If you like, you can open a pull request, just for the discussion, and we can have a look at it together, if you feel like it.
> 
> No pressure, by all means, just if you feel the need to discuss underway 😄

@erikbra I was thinking the same thing about opening a draft PR for it and we can discuss any changes further there. So I'll get that opened shortly.

**Comment by erikbra** [comment]
Great! Just ping me when you feel you have someting to discuss!
