### ISSUE TITLE
Skipped migration scripts not listed when running grate

### ISSUE THREAD

**Issue by docrinehart** [erikbra/grate#140]
**Describe the bug**
While running "dotnet grate" with only a connection string, the migrations run successfully but the skipped scripts are not listed in the tool output.

**To Reproduce**
- Create new up script
- Execute grate with connection string
- After initial execution succeeds, verify database is created/updated
- Re-execute grate
- Observe that the up script is not listed in the tool output

**Expected behavior**
Tool output should include skipped migration scripts in the console output to confirm script presence and evaluation.

**Screenshots**
![image](https://user-images.githubusercontent.com/5891405/142884712-a24346ac-eea7-4521-8002-82718b2307c8.png)

**Desktop (please complete the following information):**
 - Windows 10, Powershell 7.2,0
 - grate version v0.11.0.0 (via dotnet install to project)

**Additional context**
I was able to verify that the initial run shows the script names

![image](https://user-images.githubusercontent.com/5891405/142892148-21280374-a3c4-4efa-aaae-4242b9ee0055.png)

**Comment by erikbra** [comment]
Thank you for your report. It is actually not a bug, but a feature, as I have drowned in miles and miles of logs both in RoundhousE and helmfile (for Kubernetes changes), and been annoyed by the not-so-interesting output (for me, at that moment).

If you want to see all the lines, there's a `--verbosity` switch that will give you all the scripts, if you increase it. If I'm not mistaken, the scripts that are not run, are output with a verbosity of `Debug`, so if you wish to see them, just add a

```
--verbosity Debug
```

to your command line. 

See https://erikbra.github.io/grate/configuration-options/ for all the configuration options, or use `--help` directly.

Please let me know if it doesn't work as expected.

**Comment by docrinehart** [comment]
Good call. I guess I just got so used to seeing it by default on a lot of greenfield projects... but I can imagine that a project that's been doing it awhile could be burdensome. Not to overload this ticket then, but wouldn't it also make sense to skip output of the extra dividers and whitespace then to trim the output back?

Perhaps showing something like:
```
Looking for scripts in xxxx
--no new scripts--
```

and/or checking for a directory before output to simplify to

```
Skipping runAfterFirstUp, xxxx folder does not exist
```

**Comment by erikbra** [comment]
I definetely agree with you, @docrinehart - it would make much sense either to drop or minify the output on folders with no new scripts, or change them to make it clear that, yes, we have actually looked, but we didn't find anything new.

Same with non-existant folders. We could output that we look for them in "debug"/"verbose" mode, but not in "info" mode. 

Would you care to please formulate this in a separate issue, @docrinehart ? you do put the issues very good and precisely in wording.
