### ISSUE TITLE
Minimize console output for folders that are nonexistent or with no new scripts

### ISSUE THREAD

**Issue by docrinehart** [erikbra/grate#142]
Since grate will suppress console output for skipped files by default, it would make sense to skip output of the extra dividers and whitespace to trim unnecessary content as well. This will help to eliminate noise when verifying that scripts are detected and run appropriately.

Perhaps showing something like:
```
Looking for scripts in xxxx
--no new scripts--
```

and/or checking for a directory before output to enable simplifying the message to

```
Skipping runAfterFirstUp, xxxx folder does not exist
```

_Original comment posted by @docrinehart in https://github.com/erikbra/grate/issues/140#issuecomment-976111155_

**Comment by erikbra** [comment]
This is a good idea.

However, I have a question, do you have an idea to how we know if there are any new scripts, before we have tried running them?

**Comment by DjKillerMemeStar** [comment]
@erikbra Might be overkill, but what if we create a hash of all the files in the folders and store that somewhere?
Or even just keep track of the amount of files?

**Comment by jbergens** [comment]
+1

**Comment by wokket** [comment]
I've started looking into this, given the ease we can elevate the folder exists check [here](https://github.com/erikbra/grate/blob/main/grate/Migration/GrateMigrator.cs#L260-L264) up a method and return early we can definitely quieten the output for non existent folders, which in my sample-size of one is far more common than fully created folder heirarchies that just don't have files in them.

My big question is what log level do people feel the "Folder doesn't exist" message should be logged at?  If we log at Information than it means grate self-describes the folder options available to you when you run the tool as a new user, which I like.

Logging at Debug or lower reduces your console output by another line.

Dealing with populated folders full of files but that don't have changes is TBD (and more difficult).

**Comment by erikbra** [comment]
Great to see you have started thinking about this, @wokket !!

Could the following logic work?

* For each folder we process:
  * In the beginning, check if the folder exists. If it doesn't, only output a very minimal message, à la:
     `"Skipping runAfterFirstUp, xxxx folder does not exist".`
  * If it _does_ exist, write the same as today, `"Looking for {FolderName} scripts in \"{Path}\".{Message}"` (maybe the "Message" should be of a lower verbosity(?) - as in your link above, @wokket 
  * Make a boolean variable in `GrateMigrator.Process`, and update this on every run of a script, to see if any script was run
  * Loop through all the scripts, keep the logging in `DbMigrator.RunSql` unchanged
  * After the loop, back in `GrateMigrator.Process`, if no scripts were run, output a "--no new scripts--" message.

I would prefer to keep it at the same level as the `"Looking for {FolderName} scripts in \"{Path}\"."` message, i.e. **Information**.

**Comment by docrinehart** [comment]
@wokket / @erikbra - A bit late, but thanks for taking this on and pushing it through. Looking forward to updating my projects where I use it.
