### ISSUE TITLE
Potentially false-passing unit tests

### ISSUE THREAD

**Issue by docrinehart** [erikbra/grate#143]
When setting up the grate repo for local development, I noted that (specifically with MS SQL Server), many of the test runs resulted in failed connection attempts:

![image](https://user-images.githubusercontent.com/5891405/143307287-b325b9e9-53c0-49f0-88f8-fd9c90acb6f0.png)

However, the last few tests connected successfully, and the final test report doesn't report any test failures. I'd like to assume that the failed connect attempts were deliberate (I haven't verified by checking the unit test code yet), but I'd also assume there would only be a few of them. There were many during the initial run of "dotnet test" after cloning the repo.

![image](https://user-images.githubusercontent.com/5891405/143307567-8845dfee-d5f8-4242-b03e-524a24ee724e.png)

Opening this ticket for tracking/investigation purposes.

Relevant Tooling:
- Windows 10
- Docker Desktop with WSL2

**Comment by erikbra** [comment]
I'm pretty sure this is as expected, as we try to open a connection to the database to see if it exists, but I'll look into it. I think it's just the test output log sink that doesn't vary the output between Debug, Trace, Info, Warning, or Error severity. But I'm only 95% sure, so I'll try to look into it :)

**Comment by docrinehart** [comment]
I did a little digging myself, and I think that is correct. It looks like it just pauses briefly at a place where it shows in the output prior to logging the output from the script folder logic... I'll close for now unless something comes up since all the tests are passing.
