### ISSUE TITLE
Add grate as an Dot Net Core global tool

### ISSUE THREAD

**Issue by DjKillerMemeStar** [erikbra/grate#202]
**Is your feature request related to a problem? Please describe.**
For a project i'm working on, we use RoundhousE with the dotnet global tools to install it to the Azure Hosted Agents, this is super easy as we just need 1 command to install RoundhousE and one command to run it. No special installs or tools.

**Describe the solution you'd like**
We should make it possible to download grate as an global tool, just like RoundhousE
https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools-how-to-create

I have no clue how this works, but I'm willing to figure it out and do a pull request if this is something grate wants to support!

If we do not want to support this, add an alternative for people that work like I just described above.

**Comment by wokket** [comment]
https://erikbra.github.io/grate/getting-grate/#dotnet-tool

**Comment by DjKillerMemeStar** [comment]
Ow wauw i'm stupid. Thanks!

**Comment by erikbra** [comment]
Glad the feature was already in place :)

Would making an Azure Devops pipeline extension for grate (like this one for GitVersion, e.g? https://marketplace.visualstudio.com/items?itemName=gittools.gittools), with the parameters and everything easily available from the Azure Devops pipeline Yaml editor GUI? Or is that gold-plating?
