### ISSUE TITLE
`--dryrun` does nothing in combination with `--baseline`

### ISSUE THREAD

**Issue by aeons** [erikbra/grate#204]
**Describe the bug**
Dry running a baseline does not work.

**To Reproduce**
Run `grate -cs $CS --baseline --dryrun`. Observe that `grate` has applied the baseline to the database, created a `grate` schema, three tables and marked the migrations as run.

**Expected behavior**
`grate` prints what would happen, but does not write anything to the database.

**Comment by wokket** [comment]
Thanks for reporting this, I'll endeavour to get a fix in ASAP for you once I can find some time.
