### ISSUE TITLE
SQL Stored Procedure [schema].[storedprocname] should create the schema

### ISSUE THREAD

**Issue by OzBob** [erikbra/grate#249]
**Is your feature request related to a problem? Please describe.**
When a SQL Stored Procedure is named [schema].[storedprocname] then expect a schema to be created

**Describe the solution you'd like**
Create referenced schemas if missing:
Either examine the naming convention of the db objects, e.g sprocs
or
have a new folder called schemas

Create schemas before other objects.

**Describe alternatives you've considered**
Include a 'AlterDatabase' script that has a ```IF NOT EXISTS create schema``` statement, 

**Additional context**
The user requires additional permissions to create a schema on the destination database.

**Comment by wokket** [comment]
I have this requirement too, and just have a script in `up` that `create schema if not exists`, the same way we create tables before a sproc can reference them.

I wouldn't want to special-case ''we look inside your sql files to see if there's a schema that needs creating" when we don't do that for any other sql object.

**Comment by RachelAmbler** [comment]
I'd agree with @wokket : A schema is just another dependency that should be scripted out.

`grate` doesn't parse the contents of scripts - it just executes them. It has no way of understanding if the script is a stored procedure, a view, or even a create schema script. For all `grate` cares, the script could be a large file of multiple scripts doing different things. Not sure it would make sense to try and attempt to parse each object inside to ensure the dependencies are met like this.

This would be no different than creating table, or, even worse, creating foreign key constraint on a table with a different schema.

**Comment by erikbra** [comment]
Thanks for your insights here, @wokket and @RachelAmbler . I agree with you, and beginning to implements features related to the actual contents of the scripts is a feature creep lane I wouldn't like to go down :)

Would just scripting up the schemas solving your particular use case, @OzBob ? You shouldn't need any "if exists" either, as the script is only run once, unless you change it
