### ISSUE TITLE
Custom recreate database

### ISSUE THREAD

**Issue by kvanover** [erikbra/grate#252]
Is it possible to add a custom create database script (roundhouse -cds)?
ex -cds=createdatabase.sql

`USE master;
GO
DECLARE @Created bit
SET @Created = 0

IF NOT EXISTS(SELECT * FROM sys.databases WHERE [name] = '{{DatabaseName}}')
BEGIN
        Set @Created = 1
        CREATE DATABASE [{{DatabaseName}}]
        COLLATE Latin1_General_CI_AS
END

SELECT @Created`

Why? because we need to alter the COLLATE on creation:

ex: CREATE DATABASE [{{DatabaseName}}] COLLATE Latin1_General_CI_AS, see above

the alternative are:

1. is to add it as an option.
2. script where I can alter it, like `ALTER DATABASE [DatabaseName] COLLATE SQL_Latin1_General_CP1_CI_AS` , but I need to have the database name

**Comment by kvanover** [comment]
Tried a solution with the runAfterCreateDatabase:

`ALTER DATABASE [{{DatabaseName}}]
SET SINGLE_USER WITH ROLLBACK IMMEDIATE

ALTER DATABASE [{{DatabaseName}}]
COLLATE Latin1_General_CI_AS;

ALTER DATABASE [{{DatabaseName}}]
SET MULTI_USER`

but it failed with Resetting the connection results in a different state than the initial login. The login fails.

**Comment by wokket** [comment]
Hey mate,

Yep, it looks like that feature didn't make it [into the docco](https://erikbra.github.io/grate/migrating-from-roundhouse/#rh-features-that-arent-yet-in-grate), so it also hasn't been picked up as a job to get done here yet.  I'll label this for back-compat.

The error you're getting using `runAfterCreateDatabase` is in a similar situation to #232, would you mind trting again using grate 1.3.2 and letting us know if you get different behaviour?  SQL _may_ also want some `GO` batch separators in there, but I can't remember the requirements for those off the top of my head.

**Comment by kvanover** [comment]
Hey,

I have created a pull request for you with the changes => [https://github.com/erikbra/grate/pull/253](https://github.com/erikbra/grate/pull/253)

**Comment by erikbra** [comment]
This should be solved with #289 (not released yet - coming in 1.5)
