### ISSUE TITLE
Script runs but doesn't change the database

### ISSUE THREAD

**Issue by JordanMarr** [erikbra/grate#268]
**Describe the bug**
I am trying out grate for the first time with a pre-existing SQL Server database. 
My first and only script is `Migrations/up/'0001_Add_DrawingLogSheetNos_Id.sql` which has the following contents:

```sql
ALTER TABLE DrawingLogSheetNos
ADD Id uniqueidentifier NOT NULL DEFAULT NEWID()
```

I then run with `grate -cs "myconnstr" -f "./Migrations"`. 
According to the logs it has executed the script:

```
Looking for Update scripts in "./Migrations/up". These should be one time only scripts.
--------------------------------------------------------------------------------
  Running '0001_Add_DrawingLogSheetNos_Id.sql'.
--------------------------------------------------------------------------------
```

However, the column has not been added to the table.
(Manually executing the script, however, does work.)

What am I missing? (Note: I have never used RoundhousE before.)

**Comment by wokket** [comment]
At first glance that all seems as it should 😕

Would you mind running `grate` with the `-v Trace` param, and posting the full output here (with passwords etc redacted as needed)?
