### ISSUE TITLE
Grate should respect user terminal background

### ISSUE THREAD

**Issue by MangelMaxime** [erikbra/grate#282]
Hello

**Describe the bug**

My terminal is using a white background but Grate logging is assuming or forcing a black background. This make the output difficult to read.

**To Reproduce**

Run grate inside a terminal with a white background.

```
dotnet grate --connectionstring="Server=127.0.0.1,33300;Database=antidote;User Id=SA;Password=fakePassword;TrustServerCertificate=True" --folders=./Server/Antidote.Database/Migrations/ --noninteractive
```

**Expected behavior**

The background should not be modified by grate.

**Screenshots**

<img width="869" alt="image" src="https://user-images.githubusercontent.com/4760796/207350031-a9a70020-fb46-4bd4-91f6-e1567e9ab9b5.png">

**Desktop (please complete the following information):**
 - OS: [e.g. macOS, Linux] macOS
 - Version [e.g. 1.0.2] grate v1.4.0.0

**Comment by wokket** [comment]
I can completely understand why this would irk you!

Do you have any suggestions for how we should handle the various colour themes people use daily?  Black/white/purple/images etc are all backgrounds I've seen in use, and having a single theme to support them is clearly not going to work...

I'm hoping there's some sort of standardised BG/FG/Warning/error etc colour info avail somewhere we can use, but don't know where such a thing would live...

**Comment by MangelMaxime** [comment]
I don't think you can get the current colour of a terminal. I think each terminal emulator have their own mechanism or the ANSI colors/commands are computed during evaluation.

I think most of the tools I used only customised the foreground colour of the text they report. Like that the background is always respected.

It is not a perfect solution because if you write in green and the user has a green background the text will not be readable but I think this is how most console tools work.

**Comment by wokket** [comment]
I've just made a change to stop tinkering with the background, and it looks ok for one test in a row :D
![image](https://user-images.githubusercontent.com/3802829/209563920-422c464e-47b2-45d9-b3c4-f1560e133835.png)
