### ISSUE TITLE
Action Dry Run prompts for 'press enter'

### ISSUE THREAD

**Issue by OzBob** [erikbra/grate#301]
When running the dry-run action in the example: [grate workflow](https://github.com/erikbra/grate/blob/main/.github/workflows/grate-workflow.yml#L29)

"
Running grate v1.4.0.0 against tcp:***,1433 - ***.
Looking in ...
Please press enter when ready to kick
...
grate v1.4.0.0 has grated your database
"

Is the 'silent' property required?

**Comment by erikbra** [comment]
Yes, the `--dryrun` is meant to mimic the real thing exactly, so if you want to skip the confirmation prompt, you need to supply the `--silent` switch as well
