### ISSUE TITLE
--folders ignores 2nd++ folder

### ISSUE THREAD

**Issue by OzBob** [erikbra/grate#302]
[Specifying a custom folder configuration](https://erikbra.github.io/grate/folder-configuration/#specifying-a-custom-folder-configuration) says to use:

```--folders up=ddl;views=projections;beforemigration=preparefordeploy```

I started on case-insensitive windows folders I didn't need to specify the ```--folders```, but now implementing a Ubuntu latest on Github Action on Ubuntu Latest container, when attempting to do this:

```--folders up=Up;functions=Functions;views=Views;sprocs=Sprocs;permissions=Permissions```

the response is:

```
Looking for Update scripts in "/home/runner/work/i6osearch/i6osearch/Data/schema/db/Up". These should be one time only scripts.
--------------------------------------------------------------------------------
 Skipped ***********.sql - No changes were found to run.
...
No sql run, either an empty folder, or all files run against destination previously.
--------------------------------------------------------------------------------
                                                                                
Skipping 'Run First After Update', runFirstAfterUp does not exist.
Skipping 'Functions', functions does not exist.
Skipping 'Views', views does not exist.
Skipping 'Stored Procedures', sprocs does not exist.
Skipping 'Triggers', triggers does not exist.
Skipping 'Indexes', indexes does not exist.
Skipping 'Run after Other Anytime Scripts', runAfterOtherAnyTimeScripts does not exist.
Skipping 'Permissions', permissions does not exist.
Skipping 'AfterMigration', afterMigration does not exist.
```

If the folder values are in a 'myfolderconfig.txt' separated by a newline, it works fine.

**Comment by erikbra** [comment]
Hi, @OzBob , I'm not exactly 100% sure what you mean the issue is? Do you think grate should be case-insensitive when looking for folders? Are your folders called `Up`, `Functions`, etc, or `up`, `functions`, etc?

**Comment by OzBob** [comment]
I discovered the 'feature' when migrating my grate scripts from windows to github action.

I'm happy for you to consider a command line 'caseinsensitve' feature request, but more importantly there is a bug with the '--folders' attribute

I used the folder config text file as a workaround.


My folders are 'Up' and 'Functions' etc, so I to make grate work on Github Linux Action, I specified the '--folders' attribute in the grate command, and discoverd the reported errors.

**Comment by erikbra** [comment]
Hi, @OzBob, sorry for the late reply here. This is not a bug in grate, this is your *nix shell interpreting `;` as you wishing to end your command. Be careful to use quotes around the folder specification if you are in a shell that treats `;` specially (most shells do).

I have made a note about this in the documentation, and changed the examples to include quotes, to avoid any more mishaps here - thanks for reporting! #317
