### ISSUE TITLE
Request: improved PostgreSQL database creation experience

### ISSUE THREAD

**Issue by mattgallagher92** [erikbra/grate#307]
**Is your feature request related to a problem? Please describe.**
After [using grate to create a SQL Server database](https://www.compositional-it.com/news-blog/migration-based-database-development/), I thought I'd try doing the same for a PostgreSQL database. I installied grate as a local dotnet tool, set up a PostgreSQL database cluster (details below), and put a table creation SQL script in the up directory. Then I tried running the following command:

```bash
dotnet grate
    --databasetype postgresql
    --connectionstring 'Host=localhost;Database=my_database;Username=postgres;Password=********'
```

which gave the following error message:

>Unhandled exception: Npgsql.PostgresException (0x80004005): 3D000: database "master" does not exist

This had me stumped at first, because the equivalent works for SQL Server. After some digging around, I realised that grate tries to connect to the master database when creating a new database, by using an altered version of the given connection string targeting the master database. This is a good default for SQL Server, but not for PostgreSQL: since there is no master database to connect to in a standard PostreSQL cluster, the connection fails with the above error message.

To work around this, I provided an admin connection string targeting the postgres database that is somewhat analogous to master in SQL Server:

```bash
dotnet grate
    --databasetype postgresql
    --connectionstring 'Host=localhost;Database=my_database;Username=postgres;Password=********'
    --adminconnectionstring 'Host=localhost;Database=postgres;Username=postgres;Password=********'
```

This works great (pun intended 😆), but took a little while to get to.

>grate v1.4.0.0 has grated your database (my_database)!

**Describe the solution you'd like**
I think that the nicest solution would be for the admin connection string to default to targeting the postgres database when `--databasetype` is `postgresql`. I'm a PostgreSQL noob, but a note on the [Template Databases page of the PostgreSQL docs](https://www.postgresql.org/docs/current/manage-ag-templatedbs.html) suggests that it's ok to assume that the postgres database exists.

>The postgres database is also created when a database cluster is initialized. This database is meant as a default database for users and applications to connect to.

**Describe alternatives you've considered**
Some other possible helpful features:

- A clearer steer from the error message, indicating that grate was trying to connect to the master database so that the non-existent target database (my_database) could be created, that master was being assumed because it's appropriate for SQL Server, and that the appropriate database name could be set instead via `--adminconnectionstring`.
-  Clarification on the [configuration options page of the docs](https://erikbra.github.io/grate/configuration-options/). Perhaps the "purpose" of `--adminconnectionstring` could be changed in some way to make it clearer. For example, "Used when creating a new database, rather than migrating an existing one. Uses the value passed via `--connectionstring` with the target database changed to master, as this is appropriate for SQL Server. Must be set manually when creating new databases using other DBMSs."

**Additional context**

In case it's useful, here's the relevant section of my docker-compose.yml declaring the image containing the PostreSQL database cluster:

```yml
  db:
    image: postgres:15.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ********
```

Thanks for making and maintaining grate!

**Comment by wokket** [comment]
Good catch mate, thanks for the detailed report letting us know!

We create a swag of postgres databases in the unit tests, but it turns out they all use the `AdminConnectionString` declared [here](https://github.com/erikbra/grate/blob/f37d2b4f3f55e105089a2091bc33aaab6992e812/grate.unittests/TestInfrastructure/PostgreSqlGrateTestContext.cs#L19).

At some point I'll try and see what Sql is doing differently, although given both Erik and I are Sql Server people I'm not surprised the experience has some rough edges over here still.

If you're in a position to dig deeper and help us get a patch in that would be great(!)

**Comment by mattgallagher92** [comment]
Yeah, it makes sense that SQL Server has a smoother experience than other DBMSs given it's what you and Erik use (and given it's probably what most of your users use too). But hey, the joy of open source is that users like me can pay you guys back for your gift and easily report (and maybe smooth out) the rougher edges :slightly_smiling_face:

It's been a while since I've worked with C# (I use F# nowadays), and I'm not sure that I'm going to have much time in the next week or so, but if I get a chance I'll see if I can make some headway. But anyone else reading this who wants to take a crack, please feel free!

**Comment by mattgallagher92** [comment]
At first glance, it looks to me like the code in `grate.Configuration.GrateConfiguration.WithAdminDb` is what results in master being the assumed database for `AdminConnectionString`, but I haven't experimented to confirm.

**Comment by erikbra** [comment]
I agree with you, @mattgallagher92 , it definitely makes sense to use the `postgres` database in lieu of "master" for postgres. I think we need to introduce a new property in `ISyntax`, somenthing like `AdminDbName`, `MasterDbName`, or something, and use this property instead of the hardcoded `master` in the code snippet you reference above.

I really appreciate the thorough and detailed issue, would you like to take a shot at creating a PR as well? I would really appreciate more contributors to grate code too (even just a single PR is great!)

**Comment by mattgallagher92** [comment]
I've made [!309](https://github.com/erikbra/grate/pull/309) to improve the documentation as a stopgap measure. That should at least help anyone else out until the deeper fix you've suggested can be implemented @erikbra.

When I get time, I'll have a look at implementing the change to the code too. I'm not sure when that'll be though, it's unlikely to be in the next few days. I'm also concerned that it might take me quite a long time to get to grips with the codebase, so any further pointers to help me (or whoever picks up this change) would be appreciated :slightly_smiling_face:

**Comment by erikbra** [comment]
@mattgallagher92 - does this solve your issue? https://github.com/erikbra/grate/pull/314

**Comment by mattgallagher92** [comment]
Yes, thanks! Commented further in #310
