### ISSUE TITLE
Best practice for deploying SQL Agent Jobs

### ISSUE THREAD

**Issue by codewzrd** [erikbra/grate#330]
We have a lot of SQL Agent database jobs for our MS SQL Server databases. 

What are the best practices for deploying the SQL scripts that define the jobs?
What folder would these go in. Today we have a Jobs folder.

**Comment by erikbra** [comment]
Hi, @codewzrd - thanks for the question. There is no one, correct answer for this, and I'm not personally very familiar with SQL Agent database jobs. But, guessing, I would think these could be treated as stored procedures, with `Anytime scripts` behaviour (see)

The default folders are specified here, so if you want to stick to the default configuration, I think putting them in the `sprocs` folder would make sense: https://erikbra.github.io/grate/folder-configuration/#default-folder-configuration

However, you can customise the folders however you like, so if you prefer to have a `jobs` folder, you can specify a totally different set of folders, if you like (see link above), e.g:

`grate --folders  'tables=Once;jobs=AnyTime'`

This would expect two folders:
* tables - with One Time scripts (as `up` is in the default configuration)
* jobs - with Any Time scripts (as `sprocs` is in the default configuration

(as an example)
