### ISSUE TITLE
RoundhousE Feature | SearchAllSubdirectoriesInsteadOfTraverse

### ISSUE THREAD

**Issue by 3nth** [erikbra/grate#336]
grate is missing an option that roundhouse had, SearchAllSubdirectoriesInsteadOfTraverse

https://github.com/chucknorris/roundhouse/wiki/ConfigurationOptions

> --searchallinsteadoftraverse, --searchallsubdirectoriesinsteadoftraverse | SearchAllSubdirectoriesInsteadOfTraverse - Each Migration folder's subdirectories are traversed by default. This option pulls back scripts from the main directory and all subdirectories at once. Defaults to false. New in v0.8.5!

A faithful implementation. I come bearing branch!

Would also consider a less wordy name for the option if willing to part ways with roundhouse on this one. `IgnoreDirectoryNames`?

**Comment by erikbra** [comment]
Thank you, @3nth , I hadn't noticed that one. I guess that is a use case as well. I think I'm in favour of ignoring the extension when sorting as well. _ in a filename shoulndn't be compared to . in the extension, I agree.

**Comment by 3nth** [comment]
You're welcome!

FYI - The use case for this option is this: 

We've made a lot of migrations over time and the up folder was crowded so we started moving released migrations into a versioned subdirectory `up\1.0.0\Something.sql`

Local/Dev/etc environments usually first see those scripts straight from `up` but then later will see them again from `up/1.0.0`. With this option, moved but otherwise unchanged migrations are considered applied.

**Comment by erikbra** [comment]
Fixed in #337

**Comment by erikbra** [comment]
Ah, that makes sense, thanks for the heads-up! 

Just to understand, this also introduces a unique name constraint across all the folders, correct?

**Comment by 3nth** [comment]
Yes, you would have to have unique files across your folders with this option, since the names are presented to grate are without folders so one of them is going to fail the checksum.
