### ISSUE TITLE
MySQLConnector Hangs when connecting to MySQL 5.7 for DB Open()

### ISSUE THREAD

**Issue by John-Kryspin** [erikbra/grate#342]
**Describe the bug**
Bug is as described: https://mysqlconnector.net/troubleshooting/aurora-freeze/
Right now grate hangs on this connection opening after the "Migrating Scripts" printout

**To Reproduce**
Run grate against an MySQL Aurora 5.7 machine and the connection will hang on the Open call

**Expected behavior**
![image](https://github.com/erikbra/grate/assets/6597539/0f4918dd-4496-42a6-8db3-20bd6a857965)

**Screenshots**

**Additional context**
I think there are a few different solutions.
1. Add a tighter timeout to the Open() call
2. Add optional setting (default to false) which appends this to the connection string
3. Any other ideas @erikbra ?

I'm happy to implement some changes once we arise on the proper solution

**Comment by John-Kryspin** [comment]
I just realize that the DBconnection.Open() doesn't support cancellations or timeouts. Looks like there is some discussion about this in the MySQLConnector repo. I'm going to close this, but maybe someone will see this post in the future if they need help, the solution is to add Pipelining=False to the connection string

**Comment by erikbra** [comment]
Thanks for the comment about disabling pipelining, @John-Kryspin . We have the same issues with many of the databases trying to be clever with multiple data streams at once, with multiplexing, pipelining, pooling. But they don't work very well with grate, and we don't benefit much from them.

I have added turning off pipelining by default, if not explicitly enabled in the connection string, here: https://github.com/erikbra/grate/pull/346
