### ISSUE TITLE
Use Npgsql Code for Parsing PostgreSQL SQL Statements

### ISSUE THREAD

**Issue by Westat-Transportation** [erikbra/grate#371]
As I noted at in this [issue](https://github.com/erikbra/grate/issues/357) [comment](https://github.com/erikbra/grate/issues/357#issuecomment-1685118325), the existing RegEx based approach to split PostgreSQL commands is not working correctly with my existing db dumps (created using pg_dump 14.8 against PostgreSQL 12).

I also went back to the `grate` code on version 1.5.0 (which works with all the scripts I have) and debugged running my scripts through it.  When I did that I realized that the old RegEx simply did not parse any of the SQL statements correctly (perhaps it was copied from SQL Server?) and instead sent the entire contents of each `.sql` file to the server via Ngpsql.

More recently I went through `Npgsql`'s source code and discovered that it does not use RegEx'es to split the SQL statements, opting instead for a more elaborate approach -> [(src)](https://github.com/npgsql/npgsql/blob/main/src/Npgsql/SqlQueryParser.cs).  This was defined by one of the contributors as legacy batching of commands done by the provider and developers were encouraged to use other (more explicit) methods to conduct command batching against PostgreSql:

- https://stackoverflow.com/questions/54691579/preparing-statements-and-batching-in-npgsql
- https://www.roji.org/parameters-batching-and-sql-rewriting

Given that the underlying provider used by grate for PostgreSQL is already doing this parsing I would like to propose that we refactor its code to stop trying to parse the raw SQL loaded from `.sql` files.  If in the future `Npgsql` stops supporting raw string batching then we could consider bringing their implementation of raw SQL splitting into `grate`.

If this seems like too drastic a change I would like to propose that we at least make that available as an option via command line paramater for PostgreSQL users.  Thanks!

**Comment by Westat-Transportation** [comment]
I would also like to add that I can add the CLI switch and submit a PR if the team agrees that this is a good way to go.  Just don't want to start without first hearing from you guys because this is not a pure bug fix but rather a change in behavior / new feature.

**Comment by wokket** [comment]
Sorry for the delay getting back to you mate. I haven't been focussing on grate at all recently, so it's great to see others keen on fixing up loose ends!

Prefacing this with IANAPG (I am not a postgres guy :) ) my general feeling is:
- I'd very happy to see internal changes if we don't break back compat
- I'd prefer to minimise 'modes' of operation or switches etc if we can do without
- I'm very happy to see 3rd party logic in use which has a wider audience/is more tested rather than rolling our own

Beyond that I'm not up to date enough on teh issues or subtlies of PGsql to really have an opinion

**Comment by Westat-Transportation** [comment]
My issue is that right now I have to keep on using 1.5.0 as the versions after that attempted to implement PostgreSQL SQL parsing and ended up no longer working with my .sql files.  I can keep on using 1.5.0 for a while but eventually would like to be able to update as the versions of the packages it uses may be deprecated or found to contain security vulnerabilities.

So if you guys don't agree on a switch or a reversal of the changes done to pgsql support after 1.5.0 I may need to fork the repo and maintain our own container image for running migrations.  Right now I am relying on the 1.5.0 image on Docker Hub.

**Comment by erikbra** [comment]
Hi, guys!

A bit of other stuff going on here and there elsewhere in my life, so I haven't been able to reply to everything as quickly as I would :)

I definitely agree, that we should either just stop trying to split SQL statements if we can't do it properly, or we should do it properly. I think the "split script into multiple statements" feature is a _bit_ exotic, and, as you say, @Westat-Transportation , the feature tried to split everything using SQL server's 'GO' statement up until v 1.5.0, and was not working, so all scripts for PostgreSQL have been sent in whole files further down the pipeline, even though there might have been multiple "batches" in one file.

I don't use PostgreSQL much at all, so I don't know what people expect when using PostgreSQL. But, could you, as a PostgreSQL user, say what would make most sense, given your links in the first post here, should we just disable the batch splitting feature for PostgreSQL?

**Comment by erikbra** [comment]
Looking more into your links, the conclusion here seems to be that it's *not a good idea* for SQL drivers to parse SQL (e.g. for splitting a SQL block into multiple statements): https://github.com/npgsql/npgsql/issues/4445

As this has not been working for anything other than SQL server up until now, and I don't think it's used a lot, I'm leaning towards just turning the command batch splitting feature for anything but SQL server. 

Opinions on this, @wokket ?

**Comment by Westat-Transportation** [comment]
So, take out the batch splitting for all except for sql server?

On Sep 19, 2023, at 16:58, Erik A. Brandstadmoen ***@***.***> wrote:

﻿
CAUTION: External Email *


Looking more into your links, the conclusion here seems to be that it's not a good idea for SQL drivers to parse SQL (e.g. for splitting a SQL block into multiple statements): npgsql/npgsql#4445<https://secure-web.cisco.com/1EPuEj4iiAunzV-FRVtve4S8uGXXs8bxkjeCaqnZGpF6V8RjrQ14BorutX0IXzok0M0L4SO_FvK5x4HJpSqFqHN54LbAzwJ0yFb5FMKbjqCoTZBUEx7LOekaecVAr8FbKYzPTP_Uvp8STsGNb2kjqyPqVrBfQtiCCzBVogU5LY4l1CUqz2n4JcY1GqlXyRc8SUOVErbzYyO8gHBSSyFEAf0kAR4wzSArK79E0NhNnOHBbMp_FIxq5reB_TY5gt-og/https%3A%2F%2Fgithub.com%2Fnpgsql%2Fnpgsql%2Fissues%2F4445>

As this has not been working for anything other than SQL server up until now, and I don't think it's used a lot, I'm leaning towards just turning the command batch splitting feature for anything but SQL server.

Opinions on this, @wokket<https://secure-web.cisco.com/1uKCNg641kfHPLfnd47YzIhcMUHco55dO6jagdJssvfSeDp4O6U74OmbD9le21s7FbDfBusOYCp6Pwur1cy1QBGXukIOb0zX7hQr9TBtIV7CDbL4Y-MELXObMd7YWfUMZLM8NR5Re-K5ca_3A0pwZSqvqcC0aP4bjog7Bfsza3kRliJs6Leq4u4D6BcD-ayHfr2AJQo0h0C6DMXapG3aFoIrfmNFaZZyyKUIa4ijYpXYXXi9y6ENlj-o99HjcDxXQ/https%3A%2F%2Fgithub.com%2Fwokket> ?

—
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/1HFUHYXhVI44RLPNs0UH-5l1dnZEFl3Y2WaNTexcF2GOhHqoBmw5fUg8TwjxftjdgbiG2nhtzbgYh8yrtgMl-aiUm5U7u0kOFc9clP241fdZgUxoOL_ac3sqp2sbxVwbc-3_DY_AY_9N073h0Xi7VIG7e8YR2TM5El5QKBzmGO_4q27UrY-bo2cV0f3UX5G70aUruEatBD6Fmh_vpNHjBnkMOVIG5hhqV7rp0AE7oNTlGowC1lozAzrFUGWiIY0Il/https%3A%2F%2Fgithub.com%2Ferikbra%2Fgrate%2Fissues%2F371%23issuecomment-1726456433>, or unsubscribe<https://secure-web.cisco.com/1_yrJgSU0CXMNFhf0YzsrWsBo8EDRaz4arrXbX-voVFSRnQRc5eWuCDfFSqGsO7NwNs2S0wiPOrpC1HuvYVpABUAV9CuHqXMQQ4TpocXhPxe1hSaiPJERN71wts_6-I4Cic0SCRFVYw5vvLmJeVZFHr3EBOcAsrOG1dnwq7nMexnGIWVwpOSwYlDIjjHO4WbHjgRw2ZzMDA64UuYg6kq6UsqaP6ru-ZOvNFEKDZ6kxnFg1xOzzty9i1Zw_QChhLz6/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACEE3DLGR4YJWR2F5YFNOL3X3IBOBANCNFSM6AAAAAA43EUQRM>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

* Please use caution when responding and/or clicking on links as this email originated from outside of Westat.

**Comment by wokket** [comment]
The decision for database _drivers_ (ie Npgsql, SqlClient etc) to not do parsing/splitting/batching clearly leaves it up to the calling applications to do that.... the big question is whether we want to take that on, or push it even further up the chain to the user creating the scripts.

If this all came about because of the breaking change in PGsql concurrent batching behaviour, I'm happy to leave that with the users who can choose whether they want to take on a breaking DBMS upgrade or not, assuming we don't have other compat issues as a result.

**Comment by erikbra** [comment]
I agree with your last comment, @wokket . We are not a database driver, we are an application. However, we don't want to own all of this logic ourselves.

Please see my comment here. I don't particularly like the solution, but it works. https://github.com/erikbra/grate/pull/377#issuecomment-1726671195

An alternative is to copy the core logic from here, and put it in grate. The license is quite permissive, so that wouldn't be a problem. But, then we own the code, and we have the responsibility to maintain it as well... I don't know what I hate least.

Opinions, any of you?

**Comment by wokket** [comment]
Taking a reflection based dependency is awful...  I'd prefer to take the code as source, and maintain the source as upstream changes.  It's less brittle, provides for strong typing/compile time checks, and is less likely to impact assembly trimming in builds.  

IMHO

**Comment by erikbra** [comment]
You do make a good point, @wokket . An I'm inclined to agree. If I continue on the reflection-based approach, I still have the maintenance work continuously, but implicitly. Better then to form off this single class from the Npgsql source code, and adjust it to our needs. At least we know that the code we have is not a moving target.

**Comment by erikbra** [comment]
I have made another suggestion, where I copy the code as-is from Npgsql, and wrap a thin layer around it to perform the parsing we need. I think the result is better: https://github.com/erikbra/grate/pull/377/commits/1622c6f57054b8740011c4ca627682e056b78b2d

**Comment by erikbra** [comment]
Merged into main. Thanks for engaging, guys!

**Comment by Westat-Transportation** [comment]
Thank you for making this change!

**Comment by erikbra** [comment]
You're welcome :) Could you please just verify that version 1.5.3 works in your scenario?

**Comment by Westat-Transportation** [comment]
I will do it and get back to you here.

**Comment by Westat-Transportation** [comment]
Tested 1.5.3 on a couple of projects and it worked flawlessly! Thanks again!

**Comment by erikbra** [comment]
![image](https://github.com/erikbra/grate/assets/1628994/db2610b6-8392-43fd-ab58-34f14e301d14)
