### ISSUE TITLE
Silent flag doesn't work on version 1.5.3 on Linux

### ISSUE THREAD

**Issue by mk0sojo** [erikbra/grate#383]
**Describe the bug**
The silent flag doesn't seem to have any effect when running grate from [grate-linux-x64-self-contained-1.5.3.zip](https://github.com/erikbra/grate/releases/download/1.5.3/grate-linux-x64-self-contained-1.5.3.zip). It works in [grate-linux-x64-self-contained-1.5.2.zip](https://github.com/erikbra/grate/releases/download/1.5.2/grate-linux-x64-self-contained-1.5.2.zip). 

**To Reproduce**
1. Open in ubuntu in WSL.
2. Copy the grate file from [grate-linux-x64-self-contained-1.5.3.zip](https://github.com/erikbra/grate/releases/download/1.5.3/grate-linux-x64-self-contained-1.5.3.zip) into an empty folder and cd into it.
3. Run chmod +rwx grate.
4. Run ./grate -cs myconnection
5. You will see:
Initializing connections.
Running grate v1.5.3.0 against  - .
Looking in /home/xxx/grate for scripts to run.
Please press enter when ready to kick...

Try the same with  [grate-linux-x64-self-contained-1.5.2.zip](https://github.com/erikbra/grate/releases/download/1.5.2/grate-linux-x64-self-contained-1.5.2.zip) and it will run the script without the "Press enter prompt".
 

**Expected behavior**
The press enter prompt should not show with the silent flag

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu on WSL 2 in Windows 10
 - Version: Grate version 1.5.3

**Additional context**
I haven't tested if this is a problem on Windows.
I wonder if the .Net 8 upgrade might have anything to do with this?

**Comment by erikbra** [comment]
There is a known bug in 1.5.3. I should probably pull it from all
distributions. It doesn’t parse command line arguments correctly. Please
use 1.5.4, the error should be fixed there (the error is related to .net 8
and more aggressive assembly trimming by default)

man. 9. okt. 2023 kl. 10:09 skrev Jonas Soderholm ***@***.***

**Comment by wokket** [comment]
Just a thought for next time, we might want to consider taking a major version bump when we upgrade .Net versions commensurate with the likelyhood of bugs.

**Comment by magnusakselvoll** [comment]
@erikbra, it seems tat version 1.5.4 is not released, at least not on the release page. Currently this bug affects the current version released.

**Comment by erikbra** [comment]
@magnusakselvoll - Sorry, I had stopped in the middle of the release process (probably got lost in too many open browser tabs), but it properly out there since 1. of Nov.

**Comment by erikbra** [comment]
> Just a thought for next time, we might want to consider taking a major version bump when we upgrade .Net versions commensurate with the likelyhood of bugs.

Chicken!

No, sorry, just kidding! :) I partly agree. Or, at least test better. I don't know it changing .net versions should justify a major version number upgrade, as we compile it self-contained, and people shouldn't notice (if I test properly).

But, yes, I see your point.

I have it on my checklist to re-write the tests so that they run on the final, compiled, and trimmed product, calling it from the command-line, instead of instantiating the classes directly. This would make the tests catch these types of errors as well

**Comment by erikbra** [comment]
@mk0sojo Closing this, as the error is fixed in the newest version
