### ISSUE TITLE
A noop run creates new entries in `Version` table

### ISSUE THREAD

**Issue by devployment** [erikbra/grate#388]
**Describe the bug**
A noop run creates new entries in `Version` table

**To Reproduce**
Just run grate with no new migration added

**Expected behavior**
If nothing was migrated/executed/done, no new entry should appear in the `Version` table

**Screenshots**
<img width="1269" alt="image" src="https://github.com/erikbra/grate/assets/7137845/150aa167-9f6d-4d7b-baaa-2d7007e541ea">

<img width="738" alt="image" src="https://github.com/erikbra/grate/assets/7137845/57a9cc86-eda0-4ab7-9f88-921cbdc6dfe5">

**Desktop (please complete the following information):**

Target database: 
```
PostgreSQL 15.2 on aarch64-unknown-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit
```

Environment

```
dotnet --info
.NET SDK:
 Version:   7.0.102
 Commit:    4bbdd14480

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.5
 OS Platform: Darwin
 RID:         osx.13-arm64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.102/

Host:
  Version:      7.0.2
  Architecture: arm64
  Commit:       d037e070eb

.NET SDKs installed:
  6.0.408 [/usr/local/share/dotnet/sdk]
  7.0.102 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.16 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.16 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set
```

**Additional context**

**Comment by erikbra** [comment]
Fixed by #425
