### ISSUE TITLE
Unhandled exception trying to login to Azure SQL database

### ISSUE THREAD

**Issue by JackGraber** [erikbra/grate#421]
I'm testing out a solution using Grate (started with RH).  I'm trying to deploy to an Azure SQL Database and I get an unhandled exception with the login.

_Unhandled exception: Microsoft.Data.SqlClient.SqlException (0x80131904): Login failed for user_

My current connection string looks like this, which is one that Azure gave me for the instance. `Server=tcp:xxxxxxxx.database.windows.net,1433;Database=TestDB01;Uid=user;Pwd=xxxxxxxxxxx;Trusted_Connection=False;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;`

I've tried multiple versions of the connection string based on connectionstring.com and everything is returning the same exception.  I'm able to login to that Azure SQL DB from SSMS on my laptop.  I'm positive I'm using the correct Uid/Pwd.  

The ps1 script I'm using looks like this:
```
$ConnectionString = "Server=tcp:xxxxxxxx.database.windows.net,1433;Database=TestDB01;Uid=user;Pwd=xxxxxxxxxxx;Trusted_Connection=False;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;
$FileRoot = "C:\Code\AzureDB-test"
$FolderConfig = $FileRoot + "\FolderConfig.txt"
$Out = $FileRoot + "\MigrationOutput"


&grate --connectionstring $ConnectionString --files $FileRoot --folders $FolderConfig --version=1.0 --output $Out
```

Any suggestions would be most welcome.

Thanks!

**Comment by hoangthanh28** [comment]
Hi @JackGraber 
I can see the $ConnectionString in the PowerShell script missing " at the end. Can it be a problem?
You can try several ways below:
1. Using double quote when passing the connectionString into grate like: 
```sh
&grate --connectionstring "$ConnectionString" ...other parametter
```
2. Enable log with lower level
```sh
$env:LogLevel=Debug
&grate --connectionstring "$ConnectionString"  ...other parametter
```
3. Using docker version (it's not merged to the main branch yet). PR submitted
```sh
docker run -v $FileRoot:/db -v $Out:/output -e APP_CONNSTRING="$ConnectionString" -e VERSION=1.0 hoangthanh28/grate:latest
```

Hope it will help.

**Comment by JackGraber** [comment]
It had nothing to do with Grate.  Turns out there was a $ in the password to our Azure DB.  The powershell script was trying to read that as a variable and therefore blowing up the connection string.  After repairing the hole in the wall that my head created....it's on with more testing.  Thanks so much for the quick response and thanks for continuing to support this code base!

**Comment by erikbra** [comment]
Glad to hear you resolved it, @JackGraber  - I have done this a lot of times myself as well. It's not always easy to remember all the special characters for every shell. 

Thanks for looking into it, @hoangthanh28
