### ISSUE TITLE
Getting Incorrect string value: '\xE2\x9C\xA8", ...' for column 'text_of_script' 

### ISSUE THREAD

**Issue by Sabarinatha159** [erikbra/grate#432]
Getting the Incorrect string value: '\xE2\x9C\xA8" issue while Trying to insert query with the emojis like (✨)

Issue details
Unhandled exception: grate.Exceptions.MigrationFailed: Migration failed due to errors: 2024-02-06 21:59:20  * Incorrect string value: '\xE2\x9C\xA8", ...' for column 'text_of_script' at row 1

**Comment by erikbra** [comment]
Hi, @Sabarinatha159 , could you please tell me which database you are using?

**Comment by kitroed** [comment]
I was able to use ✨ in a sproc definition in SQL Server. UTF-8 as a default encoding is nice.

**Comment by erikbra** [comment]
This wasn't working for some of the tables, and not for all databases. Fixed in #501
