### ISSUE TITLE
Legacy `repository_path` field in Version table is unusable

### ISSUE THREAD

**Issue by kitroed** [erikbra/grate#454]
**Describe the bug**
I'm in the process of converting my old RoundhousE migrations to `grate` and I'm noticing there's no way to use the `Version.repository_path` field, and I can find no reference to it in the docs.

**To Reproduce**
Run grate command with `rh` legacy argument `--repository` and get 

"Unrecognized command or argument '--repository"

**Expected behavior**
I expected an argument to specify the value for the `repository_path` value.

**Desktop**
 - OS: Windows 11
 - Version: grate 1.6.1 - SQL Server 2017 Standard

Great work on `grate` everyone! I'm happy to see the `rh` way carried into the future!

**Comment by erikbra** [comment]
It looks like you are right, @kitroed . This is apparently an oversight when re-creating RoundhousE as grate. I find it in the RoundhousE docs here: https://github.com/chucknorris/roundhouse/wiki/ConfigurationOptions#versioning

Just our of curiosity, would you mind sharing how you use the `repository_path`? Do you actually put the repository path (source control, folder, something) in there? Or do you use it for something else?

**Comment by kitroed** [comment]
Certainly! Our team uses it to store the shared origin source control URL which helps demystify the rev hash we store in the version field.

It's possible to populate it with environment variables in Azure DevOps, which is handy.

It is helpful for noting when the version value changed from a Mercurial one to git a while back, for example.

**Comment by erikbra** [comment]
Thanks for clearing it up, @kitroed . I definitely see the point. 
I've added it to the 1.6.3 milestone. If you are able, a pull request is greatly appreciated. If not, I'll add it to the side burner, and do it when I get the time :)

**Comment by kitroed** [comment]
Thanks @erikbra, I think I'll try my hand at this.

**Comment by kitroed** [comment]
I wanted to point out that my original issue repo steps had a slight error, the original command line argument was `--repositorypath` rather than what I said, `--repository` (of which I was using the shortened `-r`).

**Comment by erikbra** [comment]
Thanks a lot for the PR, @kitroed. I have made a couple of comments.

**Comment by erikbra** [comment]
Fixed in #481
