### ISSUE TITLE
Extend GrateConfigurationBuilder with folder configuration parsing

### ISSUE THREAD

**Issue by JaDuyve** [erikbra/grate#485]
For integration tests I use Grate NuGet to apply the database migrations to the test database. I have a custom folder configuration. Because only the interfaces of folder configuration are publicly available I'm unable to create a class of `FolderConfiguration`. To be able to use `WithFolders` I needed to create my own implementation that inherits of `IFolderConfiguration`. This solution is not ideal in my opinion because it needs to be kept up-to-date with grate implementation.

https://github.com/erikbra/grate/blob/8b14721b1d8df82236f25d3602677050627e1a03/src/grate.core/Configuration/GrateConfigurationBuilder.cs#L56

### Proposed solution

Add an overload method for `WithFolders`  that accepts a string parameter which is able to do the same thing as the command line. Which accepts both semicolon separated list or path to configuration file. This solution does fit my use case because I can reuse the same folder configuration file for non test environment the migrations are not applied programmatically with the NuGet.

**Comment by erikbra** [comment]
Solved by #490 

Please see the test here, I think that will solve your issue, @JaDuyve :

https://github.com/erikbra/grate/blob/main/unittests/Basic_tests/DependencyInjection/GrateConfigurationBuilder_Factory.cs#L125
