### ISSUE TITLE
Add "--isuptodate" feature

### ISSUE THREAD

**Issue by thallesnoce** [erikbra/grate#504]
**Is your feature request related to a problem? Please describe.**
We have a pipeline that relies on RoundHouse to deploy our DB stuff.
We desire to upgrade our pipeline from RoundHouse to Grate and this flag "--isuptodate" is holding us back from doing it.

**Describe the solution you'd like**
Once we have this flag implemented on Grate, it will be possible to fully migrate and use the latest version of the tool and Azure Agents with dotnet8.

**Additional context**
Overall, congrats on the improvements, it is a great tool!

**Comment by erikbra** [comment]
Hi, @thallesnoce! 

Thanks for your input. I haven't used the `--isuptodate` option with RoundhousE, but just to double-check, the request is for grate to output text similar to the following, depending on whether the database is up-to-date or not, correct?

```bash
Database is up to date: false
-- or --
Database is up to date: true
```

Like here? https://github.com/chucknorris/roundhouse/blob/master/product/roundhouse.core/runners/RoundhouseUpdateCheckRunner.cs

Are there any other subtleties here, or is this all that is to it?

**Comment by thallesnoce** [comment]
hey @erikbra,

Thanks for the quick reply!

You are right. That is all about it.
We just need a variable from the tool that flags if the DB isuptodate or not.

Many thanks.

**Comment by Tsingis** [comment]
@erikbra is this flag missing now from documentation?

**Comment by erikbra** [comment]
Yes it is, @Tsingis . I created a new, related issue: #582
