### ISSUE TITLE
Should CONTRIBUTING.md be updated to list .NET 8

### ISSUE THREAD

**Issue by dellch** [erikbra/grate#533]
Just found this repo/tool and was browsing around.  

It looks like the `csproj` files reference .NET 8, is that true?  Should [CONTRIBUTING.md](https://github.com/erikbra/grate/blob/main/CONTRIBUTING.md) be updated for this?

I can make the PR, but wanted to check first.  The lines in `CONTRIBUTING.md`:

> ## Get .NET 6
> 
> Grate is built with .NET 6, which just shipped in early November 2021. You can get it [here](https://dotnet.microsoft.com/download/dotnet/6.0)
and start building right away.

**Comment by erikbra** [comment]
Hi, yes, you are definitely right here, @dellch. Would you like to try to fix this, and contribute with a Pull Request?

**Comment by erikbra** [comment]
I fixed it :)
