### ISSUE TITLE
GrateScritpsRun everytime i run the tool

### ISSUE THREAD

**Issue by drhamann** [erikbra/grate#544]
**Describe the bug**
I haved run the first time and everything go fine and create the tables an run the initial scripts. I 'm using this command 

```
dotnet new tool-manifest
dotnet tool install grate
dotnet tool restore
dotnet grate --connectionstring='Data Source=localhost;User=sa;Password=yourStrong(!)Password;Database=grate_test;TrustServerCertificate=True' --silent 
```

**To Reproduce**
I create a pipeline everytime somene create a script inside a up folder it runs these command again. 
Run this commands more than once, are executing the base scripts all over again

**Expected behavior**
I expecteded that the Base scripts run just once and not everytime.

**Screenshots**
![image](https://github.com/erikbra/grate/assets/23107112/2c3435ec-e3c8-4647-aa40-fa4f5af8ec87)
![image](https://github.com/erikbra/grate/assets/23107112/823d6738-466c-431b-b8fa-15d2a67d99b7)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 1.7.4
 - Sql server

**Comment by erikbra** [comment]
I think this might be a duplicate of #524, do you agree?

And, note, the **Grate**Version, **Grate**ScriptsRun, and **Grate**Version is only for the internal Grate data structure. The Version, ScriptsRun, and Version are for "your" scripts. However, it's a bug. I suspect it is related to line endings in the embedded scripts in the DLL that creates the internal structure, however, I'm not certain, I haven't had the chance to look at it properly yet

**Comment by drhamann** [comment]
Yeah, it is the same issue. I will close and comment there.
