### ISSUE TITLE
Question - How to mark one-time migration as run

### ISSUE THREAD

**Issue by mattjones0111** [erikbra/grate#546]
When applying grate to an existing codebase which already has an established schema, I'd like to create an 'initial state' migration which contains the schema creation up to that point, but not actually run it at the next deploy. How do I create a migration but mark it as already executed?

**Comment by erikbra** [comment]
That would be exactly what the `--baseline` switch does 

https://erikbra.github.io/grate/configuration-options/

**Comment by mattjones0111** [comment]
Ah. It helps to RTFM I guess. Thank you for the pointer.

**Comment by erikbra** [comment]
The manual IS a bit F here and there, and not always as easy as it should be to understand. If you have some suggestions, they are more than welcome! Glad you're helped!
