### ISSUE TITLE
Create/publish MSI

### ISSUE THREAD

**Issue by erikbra** [erikbra/grate#69]
Create installers in the `installers/msi` folder.

WIX is possibly the best alternative:
* https://wixtoolset.org/
* https://www.firegiant.com/wix/tutorial/

PROs: Free, command-line
CONs: .NET 4.x dependent (maybe harder to run in GitHub actions?

**Comment by wokket** [comment]
FWIW I have no interest in MSI's anymore, a combo of dotnet global tool and docker is all my clients are using these days, but it you wanted to support it feel free 👍

**Comment by erikbra** [comment]
Yes, I see that pov. However, dotnet global tool is dependent upon dotnet SDK, which is quite large. So it would be nice to distribute a bit more light-weight on the dependencies too. I'm thinking chocolatey, winget, etc. But they are sooooo complex. I just want to distribute a binary, ffs 😆 I see that winget supports either msi or exe distribution, but I didn't quite understand the exe one. I think it was an exe that installs your program. Which is complicated in another way.

**Comment by erikbra** [comment]
Solved with PR #74
