### ISSUE TITLE
Sign the .msi to avoid security warning

### ISSUE THREAD

**Issue by wokket** [erikbra/grate#79]
As the .msi is unsigned Windows prompts with the blue screen re: unknown publisher.

This is both a usability thing and may well prevent the installer being run in some environments which require signed installers on servers.

**Comment by wokket** [comment]
The more I think about this the more I think people are heading down the pre-built-executable/winget/docker/etc path these days.

This is still a good idea, just increasingly irrelevant.  Closing.

**Comment by erikbra** [comment]
I wholeheartedly share both your opinions on both necessity and irrelevance.
