### ISSUE TITLE
Create Wiki pages for First time user

### ISSUE THREAD

**Issue by OzBob** [erikbra/grate#97]
After using Winget or downloading the latest Release, how could a first time user with a dacpac(?) use Grate to connect to a client SQL Database, publish schema changes, and execute custom SQL data updates?

**Comment by OzBob** [comment]
Thanks for the work on the wiki and Getting Started and I look forward to exploring Grate.

I happily discovered MSBuild.Sdk.SqlProj this project for DACPAC processing by @jeffrosenberg and @ErikEJ https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/

**Comment by wokket** [comment]
If you're starting from raw .sql files then RH/grate can probably work for you, unless you have to have a .dacpac for some reason...

**Comment by OzBob** [comment]
@wokket i've got 80+ clients to distribute the latest version of the DB schema and a some data updates/migrations too. dacpac was the 'schema bit', but if i can follow the Getting Started then I'll give grate a go.

**Comment by OzBob** [comment]
404'ing on
https://github.com/erikbra/grate/blob/main/script-types/one-time
https://github.com/erikbra/grate/blob/main/script-types/anytime
on
https://github.com/erikbra/grate/blob/main/docs/GettingStarted.md

i'll come back next 'release' for some docs/guidance/examples
